### ISSUE TITLE
There are Same Elements between Category and Tag Each Post

### ISSUE THREAD

**Issue by sifnoc** [Onther-Tech/publications#3]
![image](https://user-images.githubusercontent.com/10276359/50502840-d4591400-0aa5-11e9-9bef-5cdedac1c4b7.png)

카테코리에 그래도 테그가 들어간 것 같네요.

**Comment by ggs134** [comment]
카테고리와 태그는 달라요. 그런데 대부분의 글이 두개를 같은걸 넣은게 많습니다.

**Comment by sifnoc** [comment]
네, 이슈로 남길필요는 없을것 같네요.
